title: 功能大厅
id: function
grey: true
hidden: true
content:
  # - tag: card
  #   cover: $img/tab/calendar.jpg
  #   title: 校历
  #   logo: calendar
  #   url: calendar

  # - tag: card
  #   cover: $img/tab/map.jpg
  #   title: 校园地图
  #   logo: map
  #   url: map

  # - tag: card
  #   cover: $img/tab/admission.jpg
  #   title: 录取查询
  #   logo: letter
  #   url: admission?type=search

  # - tag: card
  #   cover: $img/tab/headphone.jpg
  #   title: 音悦东师
  #   logo: cd
  #   url: music

  - tag: grid
    header: 功能
    items:
      - text: 课程表
        color: grey
        name: Course
        icon: degree
        url: course-table

      - text: 成绩查询
        color: orange
        name: Grade
        icon: grade
        url: grade-list

      - text: 学校通知
        color: red
        name: Notice
        icon: notice
        url: notice-list

      - text: 学校新闻
        color: cyan
        name: News
        icon: news
        url: notice-list?type=news

      - text: 选课系统
        color: blue
        name: Select
        icon: select
        url: select

      - text: 图书馆
        color: purple
        name: Library
        icon: library
        url: library

      - text: 体测计算器
        color: olive
        name: PE Calculator
        icon: calculate
        url: pe-calculator

  - tag: grid
    header: 信息查询
    items:
      - text: 校历
        color: olive
        name: Calendar
        icon: calendar
        url: calendar

      - text: 校园媒体
        color: grey
        name: Accounts
        icon: account
        url: school-media

      - text: 东师网站
        color: orange
        name: Websites
        icon: network
        url: website

      - text: 师大黄页
        color: purple
        name: Contact
        icon: phone
        url: phone

  - tag: grid
    header: 招生相关
    items:
      - text: 2023 年招生简章
        name: Rule
        color: blue
        icon: rule
        path: intro/enroll/under/rule/

      - text: 2023 年招生计划
        name: Plan
        color: orange
        icon: enroll
        url: enroll-plan

      - text: 历史分数
        name: History grade
        color: purple
        icon: time
        url: enroll-grade

      - text: 录取查询
        name: Admission
        color: cyan
        icon: letter
        url: admission?type=search

  - tag: grid
    header: 东师风采
    items:
      - text: 校园地图
        color: orange
        name: Map
        icon: map
        url: map

      - text: 音悦东师
        color: blue
        name: Music
        icon: cd
        url: music

      - text: 影约东师
        color: mauve
        name: Media
        icon: media
        url: video?type=video

    footer: " "
