app:
  title: 欢迎使用『东师青年+』
  content: 欢迎使用东师青年+。这是一个由校团委融媒体中心授权 Mr.Hope 个人开发制作的小程序，内含 83 万字的新生攻略。小程序内容仅代表 Mr.Hope 的个人观点，希望大家能够通过小程序摆脱对大学的迷茫。
account:
  title: 账号存储说明
  content: 您输入的账号信息仅会存储于本地，并在您删除小程序、清除微信缓存卸载微信时移除。开发者不会读取、上传您的个人信息。当且仅当您需要登录时，我们会读取您本地的账号密码，并直接转发至相关登录服务。
  force: true
