title: 首页
id: main
grey: true
hidden: true
content:
  - tag: list
    header: 纳新季
    items:
      - text: 学生组织纳新
        icon: student-org
        path: guide/organization/intake

      - text: 社团纳新
        icon: association
        path: guide/association/intake

  - tag: card
    cover: $img/tab/life.jpg
    title: 校园生活最强指南
    logo: life
    url: info?id=/guide/life/

  - tag: card
    cover: $img/tab/dining.jpg
    title: 食堂档口最强指南
    logo: dining
    url: info?id=/guide/dining/

  - tag: card
    cover: $img/tab/map.jpg
    title: 校园地图
    logo: map
    url: map

  - tag: list
    header: 疫情相关
    items:
      - text: 疫情管理调整
        icon: virus
        path: guide/epidemic/manage

      - text: 选课/注课
        icon: select
        path: guide/select/

  - tag: grid
    header: 入校介绍
    items:
      - text: 寝室
        color: blue
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: 超市
        color: olive
        name: Shop
        icon: shop
        path: guide/shop/

      - text: 洗浴
        color: red
        name: Bath
        icon: bath
        path: guide/bath/

      - text: 校园卡
        color: red
        name: Card
        icon: card
        path: guide/card/

      - text: 校园网
        color: purple
        name: Network
        icon: network
        path: guide/network/

  - tag: grid
    header: 了解学习
    items:
      - text: 专业介绍
        color: olive
        name: Major
        icon: about
        path: intro/school/major

      - text: 转专业
        color: red
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: 师范生
        color: purple
        name: Normal
        icon: teacher
        path: guide/normal/

      - text: 课程
        color: orange
        name: Course
        icon: content
        path: guide/course/

      - text: 学习
        color: mauve
        name: Study
        icon: study
        path: guide/study/

      - text: 选课
        color: cyan
        name: Select
        icon: select
        path: guide/select/

      - text: 图书馆
        color: blue
        name: Library
        icon: library
        path: intro/apt/library/

      - text: 考试
        color: olive
        name: Test
        icon: test
        path: guide/test/

    footer: 更多内容请详见下方其他 Tab 页
