title: 功能大厅
id: function
grey: true
hidden: true
content:
  - tag: card
    cover: $img/tab/calendar.jpg
    title: 校历
    logo: calendar
    url: calendar

  - tag: card
    cover: $img/tab/map.jpg
    title: 校园地图
    logo: map
    url: map

  - tag: grid
    header: false
    items:
      # - text: 校园地图
      #   color: orange
      #   name: Map
      #   icon: map
      #   url: map

      # - text: 校历
      #   color: olive
      #   name: Calendar
      #   icon: calendar
      #   url: calendar

      - text: 音悦东师
        color: blue
        name: Music
        icon: cd
        url: music

      - text: 选课系统
        color: purple
        name: Select
        icon: select
        url: select

      - text: 影约东师
        color: mauve
        name: Media
        icon: media
        url: video?type=video

      - text: 体测计算器
        color: olive
        name: PE Calculator
        icon: calculate
        url: pe-calculator

      - text: 校园媒体
        color: grey
        name: Accounts
        icon: account
        url: school-media

      - text: 东师网站
        color: orange
        name: Websites
        icon: network
        url: website

      - text: 师大黄页
        color: purple
        name: Contact
        icon: phone
        url: phone

      - text: 录取查询
        color: red
        name: Admission
        icon: letter
        url: admission?type=search
    footer: " "
